version: "3.8"

services:
  transcribe:
    build: .
    container_name: transcribe_gpu
    deploy:
      resources:
        limits:
          memory: 110G
        reservations:
          memory: 10G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true